---
- name: Safe AWS EC2 setup with key pair
  hosts: localhost
  gather_facts: false
  vars:
    key_name: sample
    instance_name: vpro-web01
    region: us-east-1
    ami_id: ami-068c0051b15cdb816

  tasks:

    # -----------------------------
    # 1️⃣ 檢查 key pair 是否存在
    # -----------------------------
    - name: Check if key pair exists
      amazon.aws.ec2_key_info:
        names:
          - "{{ key_name }}"
        region: "{{ region }}"
      register: existing_keys

    - name: Debug existing_keys
      debug:
        var: existing_keys

    # -----------------------------
    # 2️⃣ 如果 key 不存在，才建立新的 key pair
    # -----------------------------
    - name: Create EC2 key pair only if it does not exist
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
      register: keyout
      when: (existing_keys.get('keys', []) | length) == 0

    # -----------------------------
    # 3️⃣ 保存私鑰（只在第一次建立 key 時）
    # -----------------------------
    - name: Save private key content
      copy:
        content: "{{ keyout.key.key_material }}"
        dest: "./{{ key_name }}.pem"
        mode: '0600'
      when:
        - keyout is defined
        - keyout.changed
        - keyout.key.key_material is defined

    # -----------------------------
    # 4️⃣ 建立 EC2 實例
    # -----------------------------
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: t3.micro
        image_id: "{{ ami_id }}"
        wait: yes
        count: 1
        name: "{{ instance_name }}"
        tags:
          project: vprofile
        region: "{{ region }}"

